### ISSUE TITLE
Hola, una pregunta, esta API funciona?

### ISSUE THREAD

**Issue by coxato** [bytevictor/AnimeFLV-API#110]
Me he visto un poco el código, pero creo que solo trabajan con un archivo llamado `database.json` este de aqui: https://github.com/bytevictor/AnimeFLV-API/blob/master/src/api/database.json

Pero realmente cumple el objetivo que muestran en el README.md, me refiero a la motivación que exponen "Como seguidor del anime y activo usuario de esta web, me he visto en más de una ocasión refrescando una y otra vez la página para ver si había salido ya un nuevo capítulo de cualquiera fuera la serie que seguía en ese momento o pasando por 4 links diferentes para descargar algún capítulo."

Creo que tienen toda la base de código para empezar con ello pero aún no se cumple el objetivo principal que es obtener datos en tiempo real de animeflv y obtener notificaciones. O me equivoco?

**Comment by bytevictor** [comment]
Es solo una base, este proyecto se desarrolló como parte de una asignatura dedicada a la Infraestructura Virtual, es decir, el objetivo era montar integración continua, contenedores, desplegar microservicios simples, etc. Lo de "API" es una excusa ya que había que elegir un tema pero solo extrae los datos del json que enlazas. 

AnimeFLV tiene un sistema antibots que dificulta bastante hacer web scraping, aunque podría montarse una base de datos paralela con por ejemplo el webdriver de chrome, aunque cambian bastante la estructura del HTML así que hay que darle soporte continuamente.

Te paso otro repo con un proyecto que hice para descargar capítulos automáticamente que tenía puesto en privado por si te sirve.
Te aviso de que está desactualizado y hecho mal y rápido pero llegó a funcionar bien en su momento.

https://github.com/bytevictor/AnimeFLVDownloader

**Comment by coxato** [comment]
Ok, le echaré un vistazo, gracias :)
